### ISSUE TITLE
Won't run on Pop OS

### ISSUE THREAD

**Issue by Kachilero** [CS-Eevee/react-proto#91]
### Details
I downloaded the Debian installer package for Linux but on clicking on the icon nothing happens. Running the application from the terminal I got the following output
```
[1]    1742 segmentation fault (core dumped)  react-proto
```

### Expected Behavior

App should run

### Actual Behavior

App does not start, terminal outputs a segmentation fault

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

![Neofetch](https://user-images.githubusercontent.com/5316481/62699425-1c79d680-b9a5-11e9-96c0-4559a0c4babb.png)
- Node `v10.15.1`
- NPM `6.10.2`
- Ubuntu (Pop OS is based on it) `19.04`

### Steps to Reproduce

1. Download Debian package installer from link
2. Click on app icon

### Stack Trace

Terminal output when running `react-proto`
```
[1]    1742 segmentation fault (core dumped)  react-proto
```
</details>

**Comment by brianwtaylor** [comment]
hey there, appreciate you raising this issue. seems some other users have encountered some similar problems on Windows as well. Will investigate this weekend

**Comment by shreyanshu-absentia** [comment]
i am having same issue using react on debian, after checking syslog i found there is segmantation fault during startup.

>`Aug 12 16:36:59 shreyanshu-Lenovo-G570 kernel: [ 1463.370651] react-proto[3293]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffd501355f8 error 15 in react-proto[200000+160c000]
Aug 12 16:36:59 shreyanshu-Lenovo-G570 kernel: [ 1463.370657] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea
Aug 12 16:39:01 shreyanshu-Lenovo-G570 CRON[3390]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
`

**Comment by piducancore** [comment]
I'm also having this issue on debian buster.
Does anyone have any clues?

**Comment by kruglay** [comment]
Have the same issue
Ubuntu 18.10
npm 6.9.0
node v10.16.3

**Comment by viljamivirolainen** [comment]
I am having this problem after I created an arch package out of this with debtap and installed it. Installation was smooth but when I tried to run it -> segfault. 

I thought it was just because I was doing a nasty thing and converting a deb package into arch package but because debian and ubuntu users are also having problems maybe it was not that.

**Comment by brianwtaylor** [comment]
Will have this resolved in the next release for 2020.

**Comment by Elmagico1975** [comment]
Getting the same notification "Segmentation fault"

> Kali Linux 2020.1

> npm 6.13.4

> node v10.17.0

**Comment by Moshiour027** [comment]
With Ubuntu Same issue as well.

**Comment by smjacques** [comment]
Hi everyone,
Any update about fixing it? Still trying to run here with Debian. No success though.

**Comment by jlimpiado** [comment]
Any updates about this issue?

**Comment by dominikhaid** [comment]
Same error here node 15.5 debian bullseye using the .deb package.
If i use the source im getting this during the yarnrinstall process .

`make: *** [binding.target.mk:131: Release/obj.target/binding/src/binding.o] Fehler 1
make: Verzeichnis „/home/dominik/react-proto/node_modules/node-sass/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dominik/react-proto/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Linux 5.10.0-3-amd64
gyp ERR! command "/home/dominik/.nvm/versions/node/v15.5.1/bin/node" "/home/dominik/react-proto/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/dominik/react-proto/node_modules/node-sass
gyp ERR! node -v v15.5.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok make: *** [binding.target.mk:131: Release/obj.target/binding/src/binding.o] Fehler 1
make: Verzeichnis „/home/dominik/react-proto/node_modules/node-sass/build“ wird verlassen
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/dominik/react-proto/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (node:events:376:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:284:12)
gyp ERR! System Linux 5.10.0-3-amd64
gyp ERR! command "/home/dominik/.nvm/versions/node/v15.5.1/bin/node" "/home/dominik/react-proto/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /home/dominik/react-proto/node_modules/node-sass
gyp ERR! node -v v15.5.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok `

If then just yarn start it fails with the css-loader  loading the styles.css
I tried yarn upgrade but then itjust completly breaks...

**Comment by jaandrle** [comment]
Similary for me:
- Ubuntu 20.04.3 LTS (5.4.0-81-generic)
- node v16.8.0
- react-proto-1.0.0-x86_64.AppImage

```
… kernel: [ 8444.445822] react-proto[66463]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffc8c0b81b8 error 15 in react-proto[200000+160c000]
… kernel: [ 8444.445831] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea
… systemd[1271]: tmp-.mount_react\x2d00XmEQ.mount: Succeeded.
… systemd[1]: tmp-.mount_react\x2d00XmEQ.mount: Succeeded.

**Comment by VenomFate-619** [comment]
facing the same issue on popOs
![image](https://user-images.githubusercontent.com/67755128/132740850-b48a5360-def9-4282-b11e-1e52ba422ca4.png)
not opening on clicking the application icon

**Comment by letops** [comment]
Still no luck with this one?

**Comment by VenomFate-619** [comment]
Any update on this issue

**Comment by Edwin824** [comment]
Hi, I am facing the same issue.  Cannot run the app.

**Comment by crowetic** [comment]
it doesn't seem like they're developing the app anymore.
